#!/bin/tcsh
##### These lines are for Slurm
#SBATCH -N 1
#SBATCH -J mcdc_gpu_kobiashy_runtimes
#SBATCH -t 12:00:00
#SBATCH -p pbatch
#SBATCH --mail-type=ALL
#SBATCH --mail-user=morgajoa@oregonstate.edu

##### These are shell commands
date
echo ""
lscpu
echo "" 
module list
echo ""
nvidia-smi
 

conda activate mcdc-gpu

conda list

which python

echo ""
echo ""
echo ""

python run.py

echo ""
echo ""
echo "*****JOB COMPLETE******"
echo ""
echo ""
